### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#11]
The README is very basic and could use some Markdown niceness.

**Comment by kwk** [comment]
@joshuawilson if we want to stay consistent we should have a `README.adoc` instead of `README.md` just like in the core and in the devdoc project.

**Comment by joshuawilson** [comment]
@kwk I'm fine with adoc. If no one updates, I will eventually. Just thought I should post the issue if someone is looking for something simple to do.

**Comment by mindreeper2420** [comment]
Why wouldn't this stay as a markdown file, other than just because the other almighty items use ascii? This is one of the few projects I've ever seen use ascii over markdown for README files.

**Comment by aslakknutsen** [comment]
@mindreeper2420 'Just because the rest of the Team use it' sounds like a fairly compelling reason to me.. :)

**Comment by mindreeper2420** [comment]
If this is going to contributed upstream to PatternFly at some point (and why else would this project use the PatternFly styles, etc.), the files should follow that format, IMO. Things shouldn't be changed 'just because', but should be thought of in the greater context of where everything will eventually end up. Its the same process for selecting tech stacks and patterns.

**Comment by aslakknutsen** [comment]
@mindreeper2420

> If this is going to be contributed upstream to PatternFly at some point (and why else would this project use the PatternFly styles, etc.),

?

Why would the complete almighty-ui be contributed to PatternFly? Can we not use PatternFly without contributing the whole thing to PatternFly? Is not the whole point of PatternFly to provide UX Patterns/Components that can be reused by other projects? 

The almighty-ui is the UI for the almighty project. almighty is using asciidoc for docs as well as "planning" support for it in descriptions/comments/etc in the system.
RH has generally started moving to use asciidoc for docs, away from docbook. 

Now, why would we align the whole project with what a single library we use do?

> Things shouldn't be changed 'just because', 

Things are not changed just because. They were wrong, to begin with, and are now being fixed.

> the greater context of where everything will eventually end up.

Yes, and that is certainly not PatternFly. The context where it will end up is where it is already, as part of the almighty project.

**Comment by bartoszmajsak** [comment]
> I've ever seen use ascii over markdown for README files. 

Well, pro-git book for example was completely rewritten from MD to asciidoc because it's just ... better for code-oriented content.

**Comment by joshuawilson** [comment]
Whatever we want to contribute to PatternFly will need to have it's own project and therefor the work in ALMighty-UI has no effect on PatternFly.
