### ISSUE TITLE
Parameterise base URL for UI

### ISSUE THREAD

**Issue by kwk** [almighty/almighty-ui#40]
In PR #39 I quickly changed the defaults for some URLs and we might need to change this or fix the environment variable usage which was introduced by @nimishamukherjee . That doesn't seem to work.

**Comment by aslakknutsen** [comment]
```
const API_URL = process.env.API_URL = 'http://localhost:8080/api/';
```

Not sure why the AngularClass tutorial on ENV variables has this syntax. As far as I know this is not a magic if/else statement. What happen here is that process.env.API_URL is set to 'http://localhost:8080/api/' then API_URL is set to process.env.API_URL which is 'http://localhost:8080/api/'.

```js
console.log("BEFORE API_URL: " + process.env.API_URL)
const ENV = process.env.ENV = process.env.NODE_ENV = 'development';
const API_URL = process.env.API_URL = 'http://localhost:8080/api/';
const PUBLIC_PATH = process.env.PUBLIC_PATH || '/';
console.log("AFTER API_URL: " + process.env.API_URL)
```

```
BEFORE API_URL: http://demo.api.almighty.io/api/
AFTER API_URL: http://localhost:8080/api/
```

Passing in the Env variable works just fine if we don't overwrite the value :)

The webpack.prod.js file only ever attempts to use process.env.API_URL so that works fine hadn't it been for the unexplained other runtime error...

**Comment by michaelkleinhenz** [comment]
I think this is done...? See https://github.com/almighty/almighty-ui/pull/65 and the prior work. I might change the environment variable name to something more meaningful, but it works.

**Comment by nimishamukherjee** [comment]
@joshuawilson / @michaelkleinhenz what needs to be done here?

**Comment by joshuawilson** [comment]
It appears to work for now, if there are questions or issues related to this please open the issue again. Closing.
