### ISSUE TITLE
"Description"  should have word wrap limit on main page

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#87]
Steps to Create -
1. Add long description  
2. UI shows up all description on main page it should be formatted in some limited word wrap 
![screenshot from 2016-09-19 15-14-20](https://cloud.githubusercontent.com/assets/19172870/18628051/ffbc0692-7e7b-11e6-98ba-a88d0d32ed14.png)
![Uploading Screenshot from 2016-09-19 15-14-24.png…]()

**Comment by Mgranfie** [comment]
@naina-verma great catch! Is this the title or the description? The description should not display in the list view. If this is the title, it should only be one line of say 62 characters mx and then truncate, when displaying in the list. There should be a finite distance between the right side of the title and area between the next element to the right of it in the list, so that when the control re-sizes, the text truncates in a proportional way. Does this make sense? Getting this feedback in quick, so lmk if it doesn't and I can get you more info.

**Comment by naina-verma** [comment]
@Mgranfie ,
I would suggest limited number of work wrap should be better ,as title displays limited words on main page similarly Descriptions should be displaying 62(max) words and append (... Dots ) at the end of description for continue reading.

**Comment by Mgranfie** [comment]
@naina-verma I think we are saying the same thing? Let me confirm...

1. The description should not show in the list view.
2. The Title should show. 
3. The Title should display enough characters to always show at least "30" characters and then truncate with "...".
4. The title should display enough characters to leave "60" pixels between the end of the title and the first icon on the right.

These numbers are loose, trying to get the concept across and how resize will work. I have attached a couple of files. LMK if these make sense...
<img width="1015" alt="listlargersize" src="https://cloud.githubusercontent.com/assets/18149547/18671262/730ab28e-7f11-11e6-99c2-faac7c82d2c7.png">
<img width="679" alt="listsmallersize" src="https://cloud.githubusercontent.com/assets/18149547/18671265/7517fea6-7f11-11e6-93b1-e885a5a9513f.png">

**Comment by nimishamukherjee** [comment]
@Mgranfie this issue was raised on the current UI (http://demo.almighty.io/#/work-item-list).
Naina is referring to the description field. We have enabled two fields for quick add - title and description. 
It is interesting on how users are entering the PDD on the current UI. The title is a combination of PDD ID, type, and brief description. A detailed description of the PDD item is captured under the description field. 
Again this page may get invalidated based on the UX that is defined by your team.
We can keep this issue in mind when defining the description experience 
- if description is included in the list view how would it behaves
- how does the description field behave in the detailed view
etc

**Comment by Mgranfie** [comment]
@naina-verma please see the designs located here:

https://github.com/almighty/almighty-ux/issues/14

The designs are not too detailed, so please do ask away... I hope the sketches help, to start.

**Comment by Mgranfie** [comment]
@naina-verma description should not display in the list.
